[2025-05-16T05:49:37.135+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:49:37.136+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:49:37.136+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:49:37.136+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:49:37.142+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:49:37.141+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:49:37.142+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:49:37.148+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.015 seconds
[2025-05-16T05:49:50.796+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:49:50.797+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:49:50.797+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:49:50.797+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:49:50.801+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:49:50.800+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:49:50.801+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:49:50.808+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.013 seconds
[2025-05-16T05:50:21.061+0000] {processor.py:157} INFO - Started process (PID=174) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:50:21.061+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:50:21.062+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:50:21.062+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:50:21.065+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:50:21.064+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:50:21.065+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:50:21.075+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.017 seconds
[2025-05-16T05:50:51.336+0000] {processor.py:157} INFO - Started process (PID=179) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:50:51.336+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:50:51.337+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:50:51.337+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:50:51.341+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:50:51.340+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:50:51.341+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:50:51.354+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.021 seconds
[2025-05-16T05:51:21.637+0000] {processor.py:157} INFO - Started process (PID=184) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:51:21.637+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:51:21.638+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:51:21.638+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:51:21.642+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:51:21.641+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:51:21.642+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:51:21.657+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.023 seconds
[2025-05-16T05:51:51.929+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:51:51.930+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:51:51.931+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:51:51.930+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:51:51.935+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:51:51.934+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:51:51.936+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:51:51.951+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.024 seconds
[2025-05-16T05:52:22.231+0000] {processor.py:157} INFO - Started process (PID=194) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:52:22.232+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:52:22.232+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:52:22.232+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:52:22.237+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:52:22.236+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:52:22.237+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:52:22.251+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.023 seconds
[2025-05-16T05:52:52.513+0000] {processor.py:157} INFO - Started process (PID=199) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:52:52.514+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:52:52.515+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:52:52.514+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:52:52.519+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:52:52.518+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:52:52.519+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:52:52.533+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.023 seconds
[2025-05-16T05:53:22.823+0000] {processor.py:157} INFO - Started process (PID=204) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:53:22.824+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:53:22.825+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:53:22.824+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:53:22.829+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:53:22.829+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:53:22.830+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:53:22.845+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.026 seconds
[2025-05-16T05:53:53.121+0000] {processor.py:157} INFO - Started process (PID=209) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:53:53.122+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:53:53.123+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:53:53.122+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:53:53.127+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:53:53.126+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:53:53.127+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:53:53.140+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.022 seconds
[2025-05-16T05:54:23.404+0000] {processor.py:157} INFO - Started process (PID=214) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:54:23.404+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:54:23.405+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:54:23.404+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:54:23.407+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:54:23.406+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:54:23.407+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:54:23.414+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.012 seconds
[2025-05-16T05:54:34.715+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:54:34.715+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:54:34.716+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:54:34.715+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:54:34.719+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:54:34.718+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:54:34.719+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:54:34.726+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.012 seconds
[2025-05-16T05:55:04.965+0000] {processor.py:157} INFO - Started process (PID=174) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:55:04.965+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:55:04.966+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:55:04.966+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:55:04.970+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:55:04.969+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:55:04.970+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:55:04.982+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.020 seconds
[2025-05-16T05:55:35.273+0000] {processor.py:157} INFO - Started process (PID=179) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:55:35.273+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:55:35.274+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:55:35.274+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:55:35.278+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:55:35.277+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:55:35.278+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:55:35.292+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.022 seconds
[2025-05-16T05:56:05.576+0000] {processor.py:157} INFO - Started process (PID=184) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:56:05.577+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:56:05.578+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:56:05.577+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:56:05.582+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:56:05.581+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:56:05.582+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:56:05.596+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.022 seconds
[2025-05-16T05:56:35.905+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:56:35.905+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:56:35.906+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:56:35.906+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:56:35.910+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:56:35.909+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:56:35.910+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:56:35.923+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.021 seconds
[2025-05-16T05:57:06.229+0000] {processor.py:157} INFO - Started process (PID=194) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:57:06.230+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:57:06.230+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:57:06.230+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:57:06.234+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:57:06.233+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:57:06.234+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:57:06.248+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.022 seconds
[2025-05-16T05:57:36.527+0000] {processor.py:157} INFO - Started process (PID=199) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:57:36.528+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:57:36.529+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:57:36.528+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:57:36.533+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:57:36.532+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:57:36.533+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:57:36.547+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.022 seconds
[2025-05-16T05:58:06.845+0000] {processor.py:157} INFO - Started process (PID=204) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:58:06.845+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:58:06.846+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:58:06.846+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:58:06.850+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:58:06.849+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:58:06.851+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:58:06.864+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.023 seconds
[2025-05-16T05:58:37.133+0000] {processor.py:157} INFO - Started process (PID=209) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:58:37.134+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:58:37.134+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:58:37.134+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:58:37.138+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:58:37.137+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:58:37.139+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:58:37.152+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.022 seconds
[2025-05-16T05:59:07.420+0000] {processor.py:157} INFO - Started process (PID=214) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:59:07.420+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:59:07.421+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:59:07.421+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:59:07.425+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:59:07.424+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:59:07.425+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:59:07.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.019 seconds
[2025-05-16T05:59:09.444+0000] {processor.py:157} INFO - Started process (PID=219) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:59:09.445+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:59:09.445+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:59:09.445+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:59:09.452+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:59:09.450+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:59:09.453+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:59:09.468+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.028 seconds
[2025-05-16T05:59:39.781+0000] {processor.py:157} INFO - Started process (PID=224) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:59:39.782+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:59:39.783+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:59:39.783+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:59:39.787+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:59:39.786+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:59:39.788+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:59:39.803+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.025 seconds
[2025-05-16T05:59:57.294+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:59:57.295+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T05:59:57.297+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:59:57.297+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:59:57.301+0000] {logging_mixin.py:151} INFO - [2025-05-16T05:59:57.301+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T05:59:57.301+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T05:59:57.309+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.017 seconds
[2025-05-16T06:00:27.596+0000] {processor.py:157} INFO - Started process (PID=174) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:00:27.597+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:00:27.598+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:00:27.597+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:00:27.602+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:00:27.601+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:00:27.602+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:00:27.617+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.024 seconds
[2025-05-16T06:00:57.892+0000] {processor.py:157} INFO - Started process (PID=179) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:00:57.893+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:00:57.894+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:00:57.893+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:00:57.898+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:00:57.897+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 10, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:00:57.898+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:00:57.913+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.024 seconds
[2025-05-16T06:01:19.127+0000] {processor.py:157} INFO - Started process (PID=184) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:01:19.127+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:01:19.128+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:01:19.128+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:01:19.134+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:01:19.133+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 11, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:01:19.134+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:01:19.149+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.026 seconds
[2025-05-16T06:01:20.156+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:01:20.158+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:01:20.159+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:01:20.159+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:01:20.165+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:01:20.165+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:01:20.166+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:01:20.179+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.027 seconds
[2025-05-16T06:01:32.308+0000] {processor.py:157} INFO - Started process (PID=194) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:01:32.309+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:01:32.310+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:01:32.309+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:01:32.316+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:01:32.315+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:01:32.317+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:01:32.334+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.031 seconds
[2025-05-16T06:01:36.356+0000] {processor.py:157} INFO - Started process (PID=199) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:01:36.357+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:01:36.359+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:01:36.358+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:01:36.366+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:01:36.365+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:01:36.367+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:01:36.377+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.025 seconds
[2025-05-16T06:01:43.901+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:01:43.903+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:01:43.904+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:01:43.904+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:01:43.909+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:01:43.908+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:01:43.909+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:01:43.915+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.016 seconds
[2025-05-16T06:02:01.057+0000] {processor.py:157} INFO - Started process (PID=174) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:02:01.058+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:02:01.059+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:02:01.058+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:02:01.065+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:02:01.064+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:02:01.065+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:02:01.083+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.029 seconds
[2025-05-16T06:02:31.322+0000] {processor.py:157} INFO - Started process (PID=179) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:02:31.323+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:02:31.324+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:02:31.323+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:02:31.327+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:02:31.327+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:02:31.328+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:02:31.341+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.022 seconds
[2025-05-16T06:03:01.584+0000] {processor.py:157} INFO - Started process (PID=184) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:03:01.585+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:03:01.586+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:03:01.586+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:03:01.590+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:03:01.589+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:03:01.591+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:03:01.607+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.025 seconds
[2025-05-16T06:03:02.625+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:03:02.625+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:03:02.626+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:03:02.625+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:03:02.630+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:03:02.629+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:03:02.630+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:03:02.640+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.018 seconds
[2025-05-16T06:03:08.671+0000] {processor.py:157} INFO - Started process (PID=194) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:03:08.672+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:03:08.672+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:03:08.672+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:03:08.677+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:03:08.676+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:03:08.677+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:03:08.689+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.021 seconds
[2025-05-16T06:03:13.956+0000] {processor.py:157} INFO - Started process (PID=169) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:03:13.957+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:03:13.958+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:03:13.957+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:03:13.961+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:03:13.959+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:03:13.961+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:03:13.967+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.012 seconds
[2025-05-16T06:03:44.181+0000] {processor.py:157} INFO - Started process (PID=174) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:03:44.181+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:03:44.182+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:03:44.182+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:03:44.185+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:03:44.184+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:03:44.185+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:03:44.196+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.018 seconds
[2025-05-16T06:04:14.442+0000] {processor.py:157} INFO - Started process (PID=179) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:04:14.442+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:04:14.443+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:04:14.442+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:04:14.446+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:04:14.445+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:04:14.446+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:04:14.456+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.016 seconds
[2025-05-16T06:04:44.703+0000] {processor.py:157} INFO - Started process (PID=184) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:04:44.704+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:04:44.704+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:04:44.704+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:04:44.708+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:04:44.707+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:04:44.709+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:04:44.722+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.021 seconds
[2025-05-16T06:05:14.982+0000] {processor.py:157} INFO - Started process (PID=189) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:05:14.983+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:05:14.983+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:05:14.983+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:05:14.985+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:05:14.985+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:05:14.985+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:05:14.993+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.013 seconds
[2025-05-16T06:05:45.265+0000] {processor.py:157} INFO - Started process (PID=194) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:05:45.266+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:05:45.267+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:05:45.266+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:05:45.271+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:05:45.270+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:05:45.271+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:05:45.285+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.023 seconds
[2025-05-16T06:06:15.552+0000] {processor.py:157} INFO - Started process (PID=199) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:06:15.552+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:06:15.553+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:06:15.553+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:06:15.555+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:06:15.555+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:06:15.555+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:06:15.564+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.013 seconds
[2025-05-16T06:06:45.860+0000] {processor.py:157} INFO - Started process (PID=204) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:06:45.861+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:06:45.862+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:06:45.861+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:06:45.866+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:06:45.865+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:06:45.866+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:06:45.880+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.023 seconds
[2025-05-16T06:07:16.179+0000] {processor.py:157} INFO - Started process (PID=209) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:07:16.180+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:07:16.181+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:07:16.181+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:07:16.185+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:07:16.184+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:07:16.185+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:07:16.199+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.023 seconds
[2025-05-16T06:07:46.473+0000] {processor.py:157} INFO - Started process (PID=214) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:07:46.474+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:07:46.474+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:07:46.474+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:07:46.479+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:07:46.478+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:07:46.480+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:07:46.496+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.027 seconds
[2025-05-16T06:08:16.750+0000] {processor.py:157} INFO - Started process (PID=219) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:08:16.750+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:08:16.751+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:08:16.751+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:08:16.755+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:08:16.754+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:08:16.755+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:08:16.769+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.022 seconds
[2025-05-16T06:08:18.784+0000] {processor.py:157} INFO - Started process (PID=224) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:08:18.785+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:08:18.787+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:08:18.786+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:08:18.791+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:08:18.790+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 12
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))a
                                                                                ^
SyntaxError: invalid syntax
[2025-05-16T06:08:18.791+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:08:18.805+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.025 seconds
[2025-05-16T06:08:19.821+0000] {processor.py:157} INFO - Started process (PID=229) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:08:19.821+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:08:19.822+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:08:19.822+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:08:19.827+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:08:19.827+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:08:19.828+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:08:19.842+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.024 seconds
[2025-05-16T06:08:50.142+0000] {processor.py:157} INFO - Started process (PID=234) to work on /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:08:50.143+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/model_training_dag.py for tasks to queue
[2025-05-16T06:08:50.144+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:08:50.144+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:08:50.150+0000] {logging_mixin.py:151} INFO - [2025-05-16T06:08:50.149+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/model_training_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/model_training_dag.py", line 9, in <module>
    from train_model import train_model
ModuleNotFoundError: No module named 'train_model'
[2025-05-16T06:08:50.151+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/model_training_dag.py
[2025-05-16T06:08:50.165+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/model_training_dag.py took 0.027 seconds
